feat: hw10 solved
zahar517/hw-go pull request #10
Opened 2022-02-21 13:14 UTC by zahar517

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2022-02-21 13:27 UTC, zahar517 commented
Приложил [новый](new) и [старый](old) бенчмарки

2022-02-22 11:03 UTC, zahar517 commented
Приложил [новый](https://github.com/zahar517/hw-go/blob/hw10_program_optimization/hw10_program_optimization/new) и [старый](https://github.com/zahar517/hw-go/blob/hw10_program_optimization/hw10_program_optimization/old) бенчмарки

2022-02-28 16:44 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако без пройденных тестов не получится смержить PR.
Предлагаю попробовать использовать сторонний пакет анмаршаллинга
Итого: 6 баллов из 10

2022-02-28 16:44 UTC, agneum commented on hw10_program_optimization/stats.go
> +		if err := json.Unmarshal(scanner.Bytes(), &user); err != nil {
Дополнительно можно использовать сторонние пакеты анмаршаллинга, чтобы гарантированно уложиться в лимиты. Например, https://github.com/json-iterator/go, https://github.com/mailru/easyjson, https://github.com/valyala/fastjson и т. д.

2022-02-28 16:44 UTC, agneum commented on hw10_program_optimization/stats.go
> +	Address  string `json:"-"`
Предлагаю в рамках задачи убрать неиспользуемые поля

2022-03-04 15:43 UTC, agneum approved these changes
Спасибо за правки. Отличная работа
10/10

2022-03-04 16:26 UTC, merged